apiVersion: apps/v1
kind: Deployment
metadata:
  name: staffservice-deployment
  labels:
    app: staffservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staffservice
  template:
    metadata:
      labels:
        app: staffservice
    spec:
      containers:
      - name: staff-service-service
        image: stefeena/staff-service-servive:latest  # Replace with your Docker image name
        ports:
        - containerPort: 3000  # Change based on your application
---
apiVersion: v1
kind: Service
metadata:
  name: staffservice
spec:
  selector:
    app: staffservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Exposes port 3000 internally
  type: LoadBalancer
